dist: xenial
language: cpp
compiler: clang

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install g++-8 cmake doxygen graphviz -y
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 60

before_script:
  - ls
  - gcc --version
  - g++ --version
  - cmake --version

script:
- cmake .
- cmake --build .
- cmake --build . --target package
- doxygen

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: html
    on:
      branch: master
  - provider: script

  script:
  - curl -f -T print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -ustanislavkuskov:$BINTRAY_API_KEY "https://api.bintray.com/content/stanislavkuskov/otus-cpp/homework/$TRAVIS_BUILD_NUMBER/print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"
